FROM node:22-alpine AS build

USER root

RUN mkdir /app
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm@latest && \ 
    pnpm i --frozen-lockfile
COPY . .
RUN pnpm run build

FROM nginx:latest

USER root
RUN mkdir -p /app
WORKDIR /app

COPY --from=build /app/dist/ .
COPY --from=build /app/nginx.conf .

EXPOSE 3000

CMD [ "nginx", "-p", "/app", "-c", "/app/nginx.conf" ]
